### ISSUE TITLE
Can't find server node, did you press deploy?

### ISSUE THREAD

**Issue by gvdhoven** [deconz-community/node-red-contrib-deconz#206]
### Current Behavior

Everything was working fine, i updated Deconz to SQÜRL ⋅ v2.17.1 and now my Node-Red flows are not functioning anymore.

Whenever i press a (previously working) node it complains "Can't find server did you press deploy?"
And when i open the server node it _does_ automatically find the right settings.

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version: 2.3.3
- HomeKit plugin version (if used): n/a
- Node-RED version: 3.0.0
- Node.js version: unknown
- npm version: unknown
- Platform/OS: docker
- Browser: chrome

**Comment by gvdhoven** [comment]
That is the latest [docker container version](https://hub.docker.com/r/deconzcommunity/deconz/tags); 

```
RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (/data/node_modules/node-red-contrib-deconz/node_modules/got/dist/source/core/index.js:962:65)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/data/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/data/node_modules/node-red-contrib-deconz/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',

  timings: {
    start: 1658175430415,
    socket: 1658175430415,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1658175432417,
    abort: undefined,
    phases: {
      wait: 0,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2002
    }
  },
  event: 'request'
}
RequestError: Timeout awaiting 'request' for 2000ms
    at ClientRequest.<anonymous> (/data/node_modules/node-red-contrib-deconz/node_modules/got/dist/source/core/index.js:962:65)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (/data/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/data/node_modules/node-red-contrib-deconz/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',

  timings: {
    start: 1658175498008,
    socket: 1658175498008,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1658175500010,
    abort: undefined,
    phases: {
      wait: 0,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 2002
    }
  },
  event: 'request'
}
```

But the server node was configured 'automagically' so i don't understand why this error suddenly pops up. Deconz web UI is running fine.

**Comment by Zehir** [comment]
It's look like node red can't communicate with deconz.
Could you try doing a request to deconz using your browser and an http node to see what result you get
http://<deconz ip>:<deconz port>/api/config

**Comment by gvdhoven** [comment]
It boiled down to a permission error in my docker container while updating to Node-red v3.0; suggestion is to update the error message to "can't find server node ..." to "Connection to Deconz server not possible; check node-red logs" or something?
