### ISSUE TITLE
Restart node-red after add/del deconz's node

### ISSUE THREAD

**Issue by arozhankov** [deconz-community/node-red-contrib-deconz#76]
** Describe issue **
As before, an error appears when deleting / adding a node (please read log). The error causes a reboot node-red.
** Screens / Logs **

```
node-red.0 | 2020-05-08 11:24:11.706 | info | (99362) node-red exited with 1
node-red.0 | 2020-05-08 11:24:11.673 | debug | at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Socket.Readable.push (_stream_readable.js:209:10)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at readableAddChunk (_stream_readable.js:275:11)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at addChunk (_stream_readable.js:294:12)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Socket.emit (events.js:311:20)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Socket.socketOnData (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/websocket.js:875:35)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.Writable.write (_stream_writable.js:316:11)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at writeOrBuffer (_stream_writable.js:425:5)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at doWrite (_stream_writable.js:441:12)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver._write (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/receiver.js:74:10)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.startLoop (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/receiver.js:139:22)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.getData (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/receiver.js:353:17)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.dataMessage (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/receiver.js:423:14)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.emit (events.js:311:20)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at Receiver.receiverOnMessage (/opt/iobroker/iobroker-data/node-red/node_modules/ws/lib/websocket.js:800:20)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at WebSocket.emit (events.js:311:20)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at WebSocket.<anonymous> (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-deconz/lib/deconz-socket.js:59:48)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at DeconzSocket.onMessage (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-deconz/lib/deconz-socket.js:137:18)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at DeconzSocket.emit (events.js:311:20)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at DeconzSocket.<anonymous> (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-deconz/nodes/server.js:34:57)
node-red.0 | 2020-05-08 11:24:11.673 | debug | at ServerNode.onSocketMessage (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-deconz/nodes/server.js:238:38)
node-red.0 | 2020-05-08 11:24:11.673 | debug | (99362) 8 May 11:24:11 - TypeError: Cannot use 'in' operator to search for 'server' in null
node-red.0 | 2020-05-08 11:24:11.671 | debug | (99362) 8 May 11:24:11 - [red] Uncaught Exception:
node-red.0 | 2020-05-08 11:24:11.670 | debug | (99362) ERROR: cant get 487522bc.36f5ec node, removed from list
```

** Hardware / Software **
  - debian 10 + i-broker + node-red (all updated)
  - version of deconz gateway: [2.05.71 / 18/11/2019] 
  - version of node-red-contrib-deconz: [1.1.13]

**Comment by Zehir** [comment]
Did you still have the issue ?
